### ISSUE TITLE
add Add Pomf.TV extractor

### ISSUE THREAD

**Issue by DaBigBlob** [yt-dlp-archives/plugins#2]
from: https://github.com/yt-dlp/yt-dlp/pull/9251

**Comment by DaBigBlob** [comment]
@bistromathica 
if you're willing to add the extractor here, you're welcome.
The instructions are here: https://github.com/yt-dlp-archives/plugins?tab=readme-ov-file#how-do-i-add-a-new-plugin

otherwise i'll add it this by the next weekend.

**Comment by Linden10** [comment]
It's been a month, can you add the pomf.tv extractor if possible?
Thank you!

**Comment by DaBigBlob** [comment]
@Linden10 added in [b614b39](https://github.com/yt-dlp-archives/plugins/commit/b614b39ff5a6eb6c9b8120299cf859889328cae1).

**Comment by bistromathica** [comment]
I still have work to do on the Pomf extractor. Might take a look at it this weekend.
