### ISSUE TITLE
Tested the pomf.tv plugin and I found some issues!

### ISSUE THREAD

**Issue by Linden10** [yt-dlp-archives/plugins#3]
Ello, I just downloaded the plugin and tested it and I encountered errors within!

The errors were caused by the import statements being incomplete:
"from .common" and
from ..utils"

Causing this error:
`Error while importing module 'yt_dlp_plugins.extractor.pomftv'
Traceback (most recent call last):
  File "C:\Users\***\AppData\Roaming\yt-dlp\plugins\pomftv\yt_dlp_plugins\extractor\pomftv.py", line 2, in <module>
    from .common import InfoExtractor
ModuleNotFoundError: No module named 'yt_dlp_plugins.extractor.common'`

I was able to fix it easily by replacing the "from .common" and "from ..utils" lines with this:
```
from yt_dlp.extractor.common
from yt_dlp.utils
```

After that, yt-dlp finally worked and extracted the pomf.tv url properly!
However another issue cropped up, that being...the urls all give 404 errors!

For example, this url gave an 404 error:
" https://asia2.pomf.tv/hls-live/RadioSylent_hd720/index.m3u8"

So I tested the url with the list of the domains that's within the plugin py script (eu1, us1, us2, us3, etc) and all
the urls gave the same error 404 despite the streamer being live!

So I went to the livestream and checked to see how it's being streamed and what I found is that the stream is
being done through flv/mpegts format like the url below:
"https://eu1.pomf.tv/srs/live/0b2c209e76a27fff992a599b51c93f46.flv"

I'm not sure if the m3u8 urls are giving 404s just for this streamer (it could be a case by case where one streamer uses it while the others don't...IDK) or not however I do know that pomf.tv had an issue with the streaming servers last month so that might be why the m3u8 urls aren't working and thus they're using flv. (Or they always had).

Either way, even if you don't know how to resolve this I'm just here to report this! 
Happy to help and thank you!

**Comment by DaBigBlob** [comment]
hello @Linden10 
i have fixed the relative paths in https://github.com/yt-dlp-archives/plugins/commit/19085634f48a608bbb5767f9757e0486aa5502aa


i have never used pomftv before and am completely unfamiliar with it.

if you _do_ find the solution to 404 errors from the m3u8 URIs, please make a pull request.

**Comment by Linden10** [comment]
Thanks for fixing the issue! ^^

Unfortunately while I know pomf.tv, I only recently been using it as of this year so I'm unfamiliar with the site's handling of streams and such. I may contact the original creator of that plugin (if possible) if they can work/update anything on this.

Besides that, again thank you!

**Comment by bistromathica** [comment]
I still have work to do on the Pomf extractor. Will probably get to take a look at it this weekend.

**Comment by DaBigBlob** [comment]
fixed
